### PR TITLE
New design for ogImages for blog posts

### PR DESCRIPTION
**Pull request by schmidfelix**
Hey,
I've tried to make the og images for your blog posts look a bit nicer and that's what I've come up with.

I edited the colors for the different topics (laravel, php and javascript) slightly but I think it looks ok. I've got some inspiration from the new tailwindcss playground. 

**Laravel post:**
Bildschirmfoto 2020-10-08 um 09 34 13

**PHP post**
Bildschirmfoto 2020-10-08 um 09 37 01

**JavaScript**
Bildschirmfoto 2020-10-08 um 09 40 44

**Any other**
Bildschirmfoto 2020-10-08 um 09 41 56

### CODE REVIEW

**Comment by freekmurze** [comment]
This looks amazing! I'm give it a go one these days. Thank you very very much!

**Comment by freekmurze** [comment]
Thanks again!

**Comment by freekmurze** [comment]
@schmidfelix It seems that in production, the rotated background is not rendered. Could you take a look at why that doesn't work? Here's an example:
https://freek.dev/1782/og-image

**Comment by schmidfelix** [comment]
Hm, that's strange. The div gets rendered correct, but the from-xxx to-xxx classes don't do their job. 

Bildschirmfoto 2020-10-09 um 09 33 39

Are you using the latest tailwind version? And in development it worked?
On my own site I had a similar problem when compiling the css with `npm run prod` instead of `npm run dev`. How do you compile the css?

**Comment by freekmurze** [comment]
This is how the assets are built: https://github.com/spatie/freek.dev/blob/2b31b829d859dd27ad9e70c136742e97f6b61587/Envoy.blade.php#L90

Could this be a problem with PurgeCSS perhaps?

**Comment by schmidfelix** [comment]
Ah, yes that's Purge CSS. I've whitelisted the gradient classes and now it works. 
I'll send a PR. Sorry for the circumstances 😅

**Pull request merged**
