### PR TITLE
Add lazy loading to images from markdown generated content

### PR DESCRIPTION
**Pull request by robindirksen1**
Follow up from #93, some posts contain multiple images below the fold (for example: https://freek.dev/1485-my-current-setup-2019-edition).

This PR adds support for the native lazy loading feature from the browser.

### CODE REVIEW

**Comment by freekmurze** [comment]
I highly appreciate this, thanks!

**Comment by robindirksen1** [comment]
@freekmurze looks like 500 error on your home page... Can you check what's going on?

**Comment by freekmurze** [comment]
On it

**Comment by freekmurze** [comment]
Here's the exception: https://flareapp.io/share/xPQp63Rm#F58

Might be related to this PR.

**Comment by robindirksen1** [comment]
Yeah, it might be. The markdown to HTML converter misses an end `p` element, so it's generating invalid HTML.

Unfortunately, I cannot see which post on the homepage is making this exception based on the error you shared.

What do you prefer as a solution?
- try catch?
- silent the errors with `libxml_use_internal_errors`?

**Comment by freekmurze** [comment]
Just updated the code, went for a try / catch. All good now! 👍

**Review by abdullahsasc — COMMENTED** [review]
🤔

**Pull request merged**
